name: smilehighrunningclub
favicon: null
layout_spectrum: 0.3107412194367498
typography_spectrum: 0.5681010915432125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#045ebe'
    - '#09132c'
    - '#ba8068'
    - '#03a8ff'
  brandStrength: 0.9280419496353716
  lightness: 0.7093961478676647
  saturation: 0.3966148463077843
  rhythmicContrast: 0.00937638501636684
purpose: []
